import argparse

parser = argparse.ArgumentParser(description='LSHMA')
parser.add_argument('--seed', default=234, type=int)
parser.add_argument('--visual-width', default=512, type=int)
parser.add_argument('--p', default=0.0)
parser.add_argument('--visual-layers', default=4, type=int)
parser.add_argument('--attn-window', default=4, type=int)
parser.add_argument('--cache_keep_max_len', default=4, type=int)
parser.add_argument('--max-epoch', default=15, type=int)
parser.add_argument('--model-path', default='/root/LSHMA/model_ucf.pth')
parser.add_argument('--use-checkpoint', default=False, type=bool)
parser.add_argument('--checkpoint-path', default='/root/LSHMA/model/model_ucf.pth')
parser.add_argument('--batch-size', default=1, type=int)
parser.add_argument('--train-list', default='/root/LSHMA/list/ucf_CLIP_rgb.csv')
parser.add_argument('--test-list', default='/root/LSHMA/list/ucf_CLIP_rgbtest.csv')
parser.add_argument('--gt-path', default='/root/LSHMA/list/gt_ucf.npy')
# parser.add_argument('--test-list', default='/root/LSHMA/list/lt_CLIP_test.csv')
# parser.add_argument('--gt-path', default='/root/LSHMA/list/gt_lt.npy')
parser.add_argument('--lr', default=2e-5)
parser.add_argument('--scheduler-rate', default=0.1)
parser.add_argument('--scheduler-milestones', default=[3, 5])
parser.add_argument('--drop_rate', default=0.0)
parser.add_argument('--drop_attn_rate', default=0.0)
parser.add_argument('--drop_qkv_rate', default=0.0)
parser.add_argument('--keyclip_train', default=False, type=bool)
parser.add_argument('--keyclip_test', default=True, type=bool)

