import argparse

parser = argparse.ArgumentParser(description='LSHMA')
parser.add_argument('--seed', default=234, type=int)
parser.add_argument('--visual-width', default=512, type=int)
parser.add_argument('--p', default=1)
parser.add_argument('--visual-layers', default=2, type=int)
parser.add_argument('--attn-window', default=8, type=int)
parser.add_argument('--cache_keep_max_len', default=2, type=int)
parser.add_argument('--max-epoch', default=15, type=int)
parser.add_argument('--model-path', default='/root/LSHMA/model_xd.pth')
parser.add_argument('--use-checkpoint', default=False, type=bool)
parser.add_argument('--checkpoint-path', default='/root/LSHMA/model/model_xd.pth')
parser.add_argument('--batch-size', default=10, type=int)
parser.add_argument('--train-list', default='/root/LSHMA/list/xd_CLIP_rgb.csv')
parser.add_argument('--test-list', default='/root/LSHMA/list/xd_CLIP_rgbtest.csv')
parser.add_argument('--gt-path', default='/root/LSHMA/list/gt.npy')
parser.add_argument('--lr', default=1e-5)
parser.add_argument('--scheduler-rate', default=0.1)
parser.add_argument('--scheduler-milestones', default=[3, 6, 10])
parser.add_argument('--drop_rate', default=0.0)
parser.add_argument('--drop_attn_rate', default=0.0)
parser.add_argument('--drop_qkv_rate', default=0.0)
parser.add_argument('--keyclip_train', default=True, type=bool)
parser.add_argument('--keyclip_test', default=False, type=bool)
